CREATE TABLE "MEMBER" (
	"ID"	VARCHAR2(30)		NOT NULL,
	"NAME"	VARCHAR2(30)		NULL,
	"ADDRESS"	VARCHAR2(50)		NULL
);

CREATE TABLE "BOARD" (
	"BNO"	NUMBER(10)		NOT NULL,
	"TITLE"	VARCHAR2(100)		NULL,
	"CONTENT"	VARCHAR2(500)		NULL,
	"ID"	VARCHAR2(30)		NOT NULL
);

CREATE TABLE "REPLY_BOARD" (
	"NUM"	NUMBER(10)		NOT NULL,
	"TITLE"	VARCHAR2(100)		NULL,
	"CONTENT"	VARCHAR2(500)		NULL,
	"ID"	VARCHAR2(30)		NOT NULL,
	"BNO"	NUMBER(10)		NOT NULL
);

CREATE TABLE "ADMIN" (
	"ID"	VARCHAR2(30)		NOT NULL,
	"REGDATE"	DATE		NULL
);

CREATE TABLE "COURSE" (
	"CNO"	NUMBER(20)		NOT NULL,
	"CTITLE"	VARCHAR(30)		NULL,
	"CNAME"	VARCHAR(50)		NULL
);

CREATE TABLE "COURSE_LIST" (
	"ID"	VARCHAR2(30)		NOT NULL,
	"CNO"	NUMBER(20)		NOT NULL
);

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"ID"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "PK_BOARD" PRIMARY KEY (
	"BNO"
);

ALTER TABLE "REPLY_BOARD" ADD CONSTRAINT "PK_REPLY_BOARD" PRIMARY KEY (
	"NUM"
);

ALTER TABLE "ADMIN" ADD CONSTRAINT "PK_ADMIN" PRIMARY KEY (
	"ID"
);

ALTER TABLE "COURSE" ADD CONSTRAINT "PK_COURSE" PRIMARY KEY (
	"CNO"
);

ALTER TABLE "COURSE_LIST" ADD CONSTRAINT "PK_COURSE_LIST" PRIMARY KEY (
	"ID",
	"CNO"
);

ALTER TABLE "ADMIN" ADD CONSTRAINT "FK_MEMBER_TO_ADMIN_1" FOREIGN KEY (
	"ID"
)
REFERENCES "MEMBER" (
	"ID"
);

ALTER TABLE "COURSE_LIST" ADD CONSTRAINT "FK_MEMBER_TO_COURSE_LIST_1" FOREIGN KEY (
	"ID"
)
REFERENCES "MEMBER" (
	"ID"
);

ALTER TABLE "COURSE_LIST" ADD CONSTRAINT "FK_COURSE_TO_COURSE_LIST_1" FOREIGN KEY (
	"CNO"
)
REFERENCES "COURSE" (
	"CNO"
);